### ISSUE TITLE
What does this package do?

### ISSUE THREAD

**Issue by clement911** [trmcnealy/VegaLite.NET#2]
Hi.
I came across this package and I'm curious what it can be used for?

**Comment by trmcnealy** [comment]
I started building it for [Jupyter Notebooks]( https://github.com/jupyter) using [dotnet.interactive](https://github.com/dotnet/interactive) as the kernel for C#, to simplify building a chart (Generating html and embedding the data points) and try to get better performance. It's similar to [XPlot]( https://github.com/fslaborg/XPlot) but [XPlot]( https://github.com/fslaborg/XPlot) can’t handle the 400,000 data points. Unfortunately, [dotnet.interactive](https://github.com/dotnet/interactive) is a p.o.s., development is way behind all the other languages for [Jupyter Notebooks]( https://github.com/jupyter) and they hardcoded the use of RenderJS, which was pain if you want to use a JS library that also uses the function “render” for a different reason like [ArcGIS]( https://www.npmjs.com/package/arcgis-js-api). You should be able to use it with the new [WebView2]( https://docs.microsoft.com/en-us/microsoft-edge/webview2) if your data set isn’t to large. For a large data set, I would think a wasm shared memory tool is needed to help speed things up.

## Particle Swarm Optimization Results
<a href="https://raw.githubusercontent.com/trmcnealy/trmcnealy.github.io/master/Assets/PSO.mp4">
	<img src="https://raw.githubusercontent.com/trmcnealy/trmcnealy.github.io/master/Assets/PSO.png" width="100%" height="100%">
</a>

**Comment by clement911** [comment]
I see, thank you for the quick and detailed explanation.
I'm not very familiar with Jupyter notebooks but your project sounds very cool.

What I'm actually looking for is a library to generate Vega Lite graphics (svg, pdf or png) from .NET (Core).
According to https://vega.github.io/vega/usage/#node I think I'll have to somehow invoke node from .NET...

**Comment by clement911** [comment]
I'll close this issue.
