### ISSUE TITLE
Question: Vega Lite class generation

### ISSUE THREAD

**Issue by SDLWebDev** [trmcnealy/VegaLite.NET#3]
How did you generate your vega lite classes? Which tool do you use and does it support the latest vega lite json schema (http://json-schema.org/draft-07/schema#)?

I appreciate your answer :)

Best regards,
Joscha

**Comment by trmcnealy** [comment]
Using the [schema](https://vega.github.io/schema/vega-lite/v4.json) and the [quicktype](https://quicktype.io/) js script for both of my Vega projects. On my [Plotly.WPF](https://github.com/trmcnealy/Plotly.WPF) project, I started with [Plotly.Blazor](https://github.com/LayTec-AG/Plotly.Blazor) and then i ended up pulling the generator out and started to make some changes. Both generators have huge downsides but i haven't found a better option. Neither generator recursively nests types on "AnyOf"or "OneOf" json types. So you either end up with quicktype generating weird class names or Plotly.Blazor nesting at the namespace level. Both generating redundant types in different ways. Does that help?
